CREATE TABLE IF NOT EXISTS sessions (
    k  VARCHAR(64) PRIMARY KEY NOT NULL DEFAULT '',
    v  BLOB NOT NULL,
    e  BIGINT NOT NULL DEFAULT '0',
    u  TEXT
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user VARCHAR(16) UNIQUE NOT NULL,
    token VARCHAR(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS page_urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(32) NOT NULL,
    page_url VARCHAR(512) NOT NULL
);

CREATE UNIQUE INDEX user_uiq on users (user);
INSERT INTO users(user, token) VALUES ("user", "token123");